export type Tab = {
  id: string;
  isSolr?: boolean;
  table?: string;
  routeName: string;
  title: string;
  count: number;
  props: { [K: string]: any };
  fields?: string;
  objectId?: string;
};
type ResourceTabs = {
  byIds: { [K: string]: Tab };
  allIds: string[];
};

export const TABS_QUICK_SEARCH: ResourceTabs = {
  byIds: {
    locality: {
      id: "locality",
      routeName: "search-localities",
      title: "landing.localities",
      isSolr: true,
      count: 0,
      props: {},
    },
    site: {
      id: "site",
      routeName: "search-sites",
      title: "landing.sites",
      isSolr: true,
      count: 0,
      props: {},
    },
    drillcore: {
      id: "drillcore",
      routeName: "search",
      title: "landing.drillcores",
      isSolr: true,
      count: 0,
      props: {},
    },
    sample: {
      id: "sample",
      routeName: "search-samples",
      title: "landing.samples",
      isSolr: true,
      count: 0,
      props: {},
    },
    analysis: {
      id: "analysis",
      routeName: "search-analyses",
      title: "landing.analyses",
      isSolr: true,
      count: 0,
      props: {},
    },
    preparation: {
      id: "preparation",
      routeName: "search-preparations",
      title: "landing.preparations",
      isSolr: true,
      count: 0,
      props: {},
    },
    reference: {
      id: "reference",
      routeName: "search-references",
      title: "landing.references",
      isSolr: true,
      count: 0,
      props: {},
    },
    specimen: {
      id: "specimen",
      routeName: "search-specimens",
      title: "landing.specimens",
      isSolr: true,
      count: 0,
      props: {},
    },
    doi: {
      id: "doi",
      routeName: "search-dois",
      title: "landing.dois",
      isSolr: true,
      count: 0,
      props: {},
    },
    dataset: {
      id: "dataset",
      routeName: "search-datasets",
      title: "landing.datasets",
      isSolr: true,
      count: 0,
      props: {},
    },
    attachment: {
      id: "attachment",
      routeName: "search-files",
      title: "landing.attachments",
      isSolr: true,
      count: 0,
      props: {},
    },
    photo: {
      id: "photo",
      table: "attachment",
      routeName: "search-photos",
      title: "landing.photos",
      isSolr: true,
      count: 0,
      props: {},
    },
    taxon: {
      id: "taxon",
      routeName: "search-taxa",
      title: "landing.taxa",
      isSolr: true,
      count: 0,
      props: {},
    },
    rock: {
      id: "rock",
      routeName: "search-rocks",
      title: "landing.rocks",
      isSolr: true,
      count: 0,
      props: {},
    },
    stratigraphy: {
      id: "stratigraphy",
      routeName: "search-stratigraphy",
      title: "landing.stratigraphy",
      isSolr: true,
      count: 0,
      props: {},
    },
    area: {
      id: "area",
      routeName: "search-areas",
      title: "landing.areas",
      isSolr: true,
      count: 0,
      props: {},
    },
  },
  allIds: [
    "locality",
    "site",
    "drillcore",
    "sample",
    "analysis",
    "preparation",
    "reference",
    "specimen",
    "doi",
    "dataset",
    "attachment",
    "photo",
    "taxon",
    "rock",
    "stratigraphy",
    "area",
  ],
};

export const TABS_ANALYSIS: ResourceTabs = {
  byIds: {
    analysis_results: {
      id: "analysis_results",
      isSolr: true,
      routeName: "analysis-id",
      title: "analysis.results",
      count: 0,
      props: {},
    },
    attachment_link: {
      id: "attachment_link",
      routeName: "analysis-id-attachments",
      title: "analysis.attachments",
      count: 0,
      props: {},
    },
  },
  allIds: ["analysis_results", "attachment_link"],
};

export const TABS_AREA: ResourceTabs = {
  byIds: {
    site: {
      id: "site",
      isSolr: true,
      routeName: "area-id",
      title: "area.sites",
      count: 0,
      props: {},
    },
    locality_reference: {
      id: "locality_reference",
      routeName: "area-id-references",
      title: "area.localityReferences",
      count: 0,
      props: {},
    },
    relatedArea: {
      id: "relatedArea",
      table: "area",
      routeName: "area-id-related-areas",
      title: "area.relatedAreas",
      count: 0,
      props: {},
    },
    locality: {
      id: "locality",
      table: "locality",
      routeName: "area-id-localities",
      title: "area.localities",
      count: 0,
      props: {},
    },
  },
  allIds: ["site", "locality_reference", "relatedArea", "locality"],
};

export const TABS_COLLECTION: ResourceTabs = {
  byIds: {
    specimen: {
      id: "specimen",
      isSolr: true,
      routeName: "collection-id",
      title: "collection.specimens",
      count: 0,
      props: {},
    },
  },
  allIds: ["specimen"],
};

export const TABS_DATASET: ResourceTabs = {
  byIds: {
    sample_results: {
      id: "sample_results",
      table: "sample_data",
      isSolr: true,
      routeName: "dataset-id",
      title: "dataset.sampleResults",
      count: 0,
      props: {},
    },
    graphs: {
      table: "analysis_results",
      id: "graphs",
      isSolr: true,
      routeName: "dataset-id-graphs",
      title: "locality.graphs",
      count: 0,
      props: {},
    },
    dataset_analysis: {
      id: "dataset_analysis",
      table: "analytical_data",
      isSolr: true,
      routeName: "dataset-id-analyses",
      title: "dataset.analyses",
      count: 0,
      props: {},
    },
    dataset_reference: {
      id: "dataset_reference",
      table: "dataset_reference",
      routeName: "dataset-id-references",
      title: "dataset.references",
      count: 0,
      props: {},
    },
    attachment_link: {
      id: "attachment_link",
      table: "attachment_link",
      routeName: "dataset-id-attachments",
      title: "dataset.attachments",
      count: 0,
      props: {},
    },
    dataset_author: {
      id: "dataset_author",
      table: "dataset_author",
      routeName: "dataset-id-authors",
      title: "dataset.authors",
      count: 0,
      props: {},
    },
    dataset_geolocation: {
      id: "dataset_geolocation",
      table: "dataset_geolocation",
      routeName: "dataset-id-geolocations",
      title: "dataset.geolocations",
      count: 0,
      props: {},
    },
  },
  allIds: [
    "sample_results",
    "graphs",
    "dataset_analysis",
    "dataset_reference",
    "attachment_link",
    "dataset_author",
    "dataset_geolocation",
  ],
};

export const TABS_DRILLCORE: ResourceTabs = {
  byIds: {
    boxes: {
      id: "boxes",
      table: "drillcore_box",
      routeName: "drillcore-id",
      title: "drillcore.drillcoreBoxesTitle",
      count: 0,
      props: {},
    },
    locality_description: {
      id: "locality_description",
      routeName: "drillcore-id-descriptions",
      title: "drillcore.localityDescriptions",
      count: 0,
      props: {},
    },
    locality_reference: {
      id: "locality_reference",
      routeName: "drillcore-id-references",
      title: "drillcore.localityReferences",
      count: 0,
      props: {},
    },
    attachment_link: {
      id: "attachment_link",
      routeName: "drillcore-id-attachments",
      title: "drillcore.attachments",
      count: 0,
      props: {},
    },
    sample: {
      id: "sample",
      isSolr: true,
      routeName: "drillcore-id-samples",
      title: "drillcore.samples",
      count: 0,
      props: {},
    },
    analysis: {
      id: "analysis",
      isSolr: true,
      routeName: "drillcore-id-analyses",
      title: "drillcore.analyses",
      count: 0,
      props: {},
    },
    specimen: {
      id: "specimen",
      isSolr: true,
      routeName: "drillcore-id-specimens",
      title: "drillcore.specimens",
      count: 0,
      props: {},
    },
    analysis_results: {
      table: "analysis_results",
      id: "analysis_results",
      isSolr: true,
      routeName: "drillcore-id-graphs",
      title: "locality.graphs",
      count: 0,
      props: {},
    },
  },
  allIds: [
    "boxes",
    "locality_description",
    "locality_reference",
    "attachment_link",
    "sample",
    "analysis",
    "specimen",
    "analysis_results",
  ],
};

export const TABS_DRILLCORE_BOX: ResourceTabs = {
  byIds: {
    sample: {
      id: "sample",
      routeName: "drillcore-box-id",
      isSolr: true,
      title: "drillcore.samples",
      count: 0,
      props: {},
    },
    analysis: {
      id: "analysis",
      routeName: "drillcore-box-id-analyses",
      title: "drillcore.analyses",
      isSolr: true,
      count: 0,
      props: {},
    },
    specimen: {
      id: "specimen",
      routeName: "drillcore-box-id-specimens",
      title: "drillcore.specimens",
      isSolr: true,
      count: 0,
      props: {},
    },
  },
  allIds: ["sample", "analysis", "specimen"],
};

export const TABS_LOCALITY: ResourceTabs = {
  byIds: {
    locality_reference: {
      id: "locality_reference",
      routeName: "locality-id",
      title: "locality.references",
      count: 0,
      props: {},
    },
    locality_description: {
      id: "locality_description",
      routeName: "locality-id-descriptions",
      title: "locality.descriptions",
      count: 0,
      props: {},
    },
    attachment_link: {
      id: "attachment_link",
      routeName: "locality-id-attachments",
      title: "locality.attachments",
      count: 0,
      props: {},
    },
    sample: {
      id: "sample",
      routeName: "locality-id-samples",
      title: "locality.samples",
      isSolr: true,
      count: 0,
      props: {},
    },
    boxes: {
      id: "boxes",
      table: "drillcore_box",
      routeName: "locality-id-drillcore-boxes",
      title: "locality.drillcoreBoxes",
      count: 0,
      props: {},
    },
    fossils: {
      id: "fossils",
      routeName: "locality-id-fossils",
      title: "locality.fossils",
      table: "taxon_search",
      isSolr: true,
      count: 0,
      props: {},
    },
    specimen: {
      id: "specimen",
      routeName: "locality-id-specimens",
      title: "locality.specimens",
      isSolr: true,
      count: 0,
      props: {},
    },
    locality_synonym: {
      id: "locality_synonym",
      routeName: "locality-id-synonyms",
      title: "locality.synonyms",
      count: 0,
      props: {},
    },
    stratigraphy_stratotype: {
      id: "stratigraphy_stratotype",
      routeName: "locality-id-stratotypes",
      title: "locality.stratotypes",
      count: 0,
      props: {},
    },
    analysis: {
      id: "analysis",
      isSolr: true,
      routeName: "locality-id-analyses",
      title: "locality.analyses",
      count: 0,
      props: {},
    },
    analysis_results: {
      table: "analysis_results",
      id: "graphs",
      isSolr: true,
      routeName: "locality-id-graphs",
      title: "locality.graphs",
      count: 0,
      props: {},
    },
  },
  allIds: [
    "locality_reference",
    "locality_description",
    "attachment_link",
    "sample",
    "boxes",
    "fossils",
    "specimen",
    "locality_synonym",
    "stratigraphy_stratotype",
    "analysis",
    "analysis_results",
  ],
};

export const TABS_PREPARATION: ResourceTabs = {
  byIds: {
    attachment_link: {
      id: "attachment_link",
      routeName: "preparation-id",
      title: "preparation.attachments",
      count: 0,
      props: {},
    },
    taxon_list: {
      id: "taxon_list",
      isSolr: false,
      routeName: "preparation-id-taxa",
      title: "preparation.taxa",
      count: 0,
      props: {},
    },
  },
  allIds: ["attachment_link", "taxon_list"],
};

export const TABS_SAMPLE: ResourceTabs = {
  byIds: {
    analysis: {
      id: "analysis",
      isSolr: true,
      routeName: "sample-id",
      title: "sample.analyses",
      count: 0,
      props: {},
    },
    preparation: {
      id: "preparation",
      isSolr: true,
      routeName: "sample-id-preparations",
      title: "sample.preparations",
      count: 0,
      props: {},
    },
    taxon_list: {
      id: "taxon_list",
      routeName: "sample-id-taxa",
      title: "sample.taxa",
      count: 0,
      props: {},
    },
    attachment_link: {
      id: "attachment_link",
      routeName: "sample-id-attachments",
      title: "sample.attachments",
      count: 0,
      props: {},
    },
    sample_reference: {
      id: "sample_reference",
      routeName: "sample-id-references",
      title: "sample.sampleReferences",
      count: 0,
      props: {},
    },
    analysis_results: {
      id: "analysis_results",
      isSolr: true,
      routeName: "sample-id-analysis-results",
      title: "sample.analysisResults",
      count: 0,
      props: {},
    },
    graphs: {
      table: "taxon_list",
      id: "graphs",
      routeName: "sample-id-graphs",
      title: "locality.graphs",
      count: 0,
      props: {},
    },
  },
  allIds: [
    "analysis",
    "preparation",
    "taxon_list",
    "attachment_link",
    "sample_reference",
    "analysis_results",
    "graphs",
  ],
};

export const TABS_SITE: ResourceTabs = {
  byIds: {
    attachment_link: {
      id: "attachment_link",
      routeName: "site-id",
      title: "site.attachments",
      count: 0,
      props: {},
    },
    sample: {
      id: "sample",
      isSolr: true,
      routeName: "site-id-samples",
      title: "site.samples",
      count: 0,
      props: {},
    },
    locality_description: {
      id: "locality_description",
      routeName: "site-id-descriptions",
      title: "site.localityDescriptions",
      count: 0,
      props: {},
    },
    locality_reference: {
      id: "locality_reference",
      routeName: "site-id-references",
      title: "site.localityReferences",
      count: 0,
      props: {},
    },
  },
  allIds: [
    "attachment_link",
    "sample",
    "locality_description",
    "locality_reference",
  ],
};

export const TABS_SPECIMEN: ResourceTabs = {
  byIds: {
    specimen_identification: {
      id: "specimen_identification",
      table: "specimen_identification",
      isSolr: false,
      routeName: "specimen-id",
      title: "specimen.identifications",
      count: 0,
      props: {},
    },
    specimen_identification_geology: {
      id: "specimen_identification_geology",
      table: "specimen_identification_geology",
      isSolr: false,
      routeName: "specimen-id-rock-identifications",
      title: "specimen.rockIdentifications",
      count: 0,
      props: {},
    },
    specimen_reference: {
      id: "specimen_reference",
      table: "specimen_reference",
      isSolr: false,
      routeName: "specimen-id-references",
      title: "specimen.references",
      count: 0,
      props: {},
    },
  },
  allIds: [
    "specimen_identification",
    "specimen_identification_geology",
    "specimen_reference",
  ],
};

export const TABS_STRATIGRAPHY: ResourceTabs = {
  byIds: {
    stratigraphy_reference: {
      id: "stratigraphy_reference",
      table: "stratigraphy_reference",
      routeName: "stratigraphy-id",
      title: "stratigraphy.references",
      count: 0,
      props: {},
      fields: "reference_id",
    },
    stratigraphy_synonym: {
      id: "stratigraphy_synonym",
      table: "stratigraphy_synonym",
      routeName: "stratigraphy-id-synonyms",
      title: "stratigraphy.synonyms",
      count: 0,
      props: {},
    },
    subunits: {
      id: "subunits",
      table: "stratigraphy",
      routeName: "stratigraphy-id-subunits",
      title: "stratigraphy.subUnits",
      isSolr: true,
      count: 0,
      props: {},
    },
    lithostratigraphy: {
      id: "lithostratigraphy",
      table: "stratigraphy",
      routeName: "stratigraphy-id-related-units",
      title: "stratigraphy.relatedUnits",
      isSolr: true,
      count: 0,
      props: {},
    },
    specimen: {
      id: "specimen",
      table: "specimen",
      routeName: "stratigraphy-id-specimens",
      title: "stratigraphy.specimens",
      isSolr: true,
      count: 0,
      props: {},
    },
    sample: {
      id: "sample",
      table: "sample",
      routeName: "stratigraphy-id-samples",
      title: "stratigraphy.samples",
      isSolr: true,
      count: 0,
      props: {},
    },
  },
  allIds: [
    "stratigraphy_reference",
    "stratigraphy_synonym",
    "subunits",
    "lithostratigraphy",
    "specimen",
    "sample",
  ],
};
