export const SET_MODULE_ITEMS = 'SET_MODULE_ITEMS'
export const SET_MODULE_COUNT = 'SET_MODULE_COUNT'
export const SET_MODULE_OPTIONS = 'SET_MODULE_OPTIONS'
export const RESET_MODULE_FILTERS = 'RESET_MODULE_FILTERS'

export const RESET_INSTITUTIONS = 'RESET_INSTITUTIONS'
export const RESET_GEOJSON = 'RESET_GEOJSON'
export const RESET_SEARCH_QUERY = 'RESET_SEARCH_QUERY'

// ANALYTICAL DATA

export const UPDATE_PARAMETER = 'UPDATE_PARAMETER'
export const SET_LIST_PARAMETERS = 'SET_LIST_PARAMETERS'
export const UPDATE_ANALYTICAL_DATA_HEADERS = 'UPDATE_ANALYTICAL_DATA_HEADERS'
export const SET_SHOWN_ACTIVE_LIST_PARAMETERS =
  'SET_SHOWN_ACTIVE_LIST_PARAMETERS'
export const INIT_ACTIVE_LIST_PARAMETERS = 'INIT_ACTIVE_LIST_PARAMETERS'
export const ADD_ACTIVE_LIST_PARAMETER = 'ADD_ACTIVE_LIST_PARAMETER'
export const REMOVE_ACTIVE_LIST_PARAMETER = 'REMOVE_ACTIVE_LIST_PARAMETER'
export const UPDATE_ACTIVE_LIST_PARAMETERS = 'UPDATE_ACTIVE_LIST_PARAMETERS'
export const UPDATE_ACTIVE_PARAM = 'UPDATE_ACTIVE_PARAM'
export const UPDATE_ACTIVE_LIST_PARAMETERS_FILTERS =
  'UPDATE_ACTIVE_LIST_PARAMETERS_FILTERS'
export const REMOVE_ACTIVE_LIST_PARAMETER_FILTER =
  'REMOVE_ACTIVE_LIST_PARAMETER_FILTER'

// TABLE HEADERS

export const SET_ALL_FIELD_NAMES = 'SET_ALL_FIELD_NAMES'
export const SET_TABLE_HEADERS = 'SET_TABLE_HEADERS'
export const UPDATE_TABLE_HEADERS = 'UPDATE_TABLE_HEADERS'

// HISTORY

export const PUSH_HISTORY = 'PUSH_HISTORY'
