export const SET_MODULE_ITEMS = 'SET_MODULE_ITEMS'
export const SET_MODULE_COUNT = 'SET_MODULE_COUNT'
export const SET_MODULE_OPTIONS = 'SET_MODULE_OPTIONS'
export const RESET_MODULE_FILTERS = 'RESET_MODULE_FILTERS'
export const RESET_MODULE_QUERY = 'RESET_MODULE_QUERY'
export const RESET_MODULE_OPTIONS = 'RESET_MODULE_OPTIONS'

export const RESET_INSTITUTIONS = 'RESET_INSTITUTIONS'
export const RESET_GEOJSON = 'RESET_GEOJSON'
export const RESET_QUERY = 'RESET_QUERY'

// HISTORY
export const PUSH_HISTORY = 'PUSH_HISTORY'

// MAP
export const SET_BASE_LAYER = 'SET_BASE_LAYER'

// HEADERS
export const TOGGLE_HEADER = 'TOGGLE_HEADER'
export const RESET_HEADERS = 'RESET_HEADERS'

// SEARCH/ANALYTICAL_DATA
export const SET_PARAMETERS = 'SET_PARAMETERS'
export const ADD_PARAMETER_FILTER = 'ADD_PARAMETER_FILTER'
export const UPDATE_PARAMETER_FILTER = 'UPDATE_PARAMETER_FILTER'
export const REMOVE_PARAMETER_FILTER = 'REMOVE_PARAMETER_FILTER'
